### PR TITLE
Adds feature to cancel sorting.

### LINKED ISSUE #21: [Feature request] "Unsort" column
At the moment it is possible to sort a column by repeatedly clicking on the header. I could not find a way to remove the sorting and display the data in its original order.

I can think of two approaches:
1. Cycle through `Sort ascending` > `Sort descending` > `Unsorted` for each click on the header.
2. Use a modifier key (`Ctrl` or `Shift`?) to remove the sorting from the column.

### PR DESCRIPTION
**Pull request by sphh**
Right-clicking on a sorted column header will cancel sorting. (Closes #21)

### CODE REVIEW

**Comment by driscollis** [comment]
Did you try running the test suite to see if this breaks anything?

**Comment by sphh** [comment]
I just did it: I get 30 fails and 101 passes. The only one, which has `sort` in it, is this:
```
FAILED test/test_ObjectListView.py::TestVirtualObjectListView::testSorting - wx._core.wxAssertionError: C++ assertion "lineTo < GetItemCount()" failed at /home/wxpy/wxPython-4.2.0/ext/wxWidgets/src/generic/listctrl.cpp(1966) in RefreshLines(): invalid line range
```
but IIRC, this was the same before I did these changes.

**Comment by driscollis** [comment]
> I just did it: I get 30 fails and 101 passes. The only one, which has `sort` in it, is this:
> 
> ```
> FAILED test/test_ObjectListView.py::TestVirtualObjectListView::testSorting - wx._core.wxAssertionError: C++ assertion "lineTo < GetItemCount()" failed at /home/wxpy/wxPython-4.2.0/ext/wxWidgets/src/generic/listctrl.cpp(1966) in RefreshLines(): invalid line range
> ```
> 
> but IIRC, this was the same before I did these changes.

I am going to try to find a way to run this PR against main as I got all the tests passing last week and I don't want to introduce any new defects

**Comment by driscollis** [comment]
Hmmm....I think I fixed all the errors I am currently seeing in your code. Could you resync your branch for me so it has my latest changes and then I can re-run the tests?

**Comment by sphh** [comment]
I am afraid, that I do not entirely understand, what you want me to do (and my understanding of git is just good enough, to make an occasional PR). Could you please help me with a list of git commands to run?

**Comment by driscollis** [comment]
Actually, after rechecking this, I think it will merge fine without syncing. However, there should be a "resync" button on your fork that you could use if you need to

**Pull request merged**
